//
//  ConfigurableView.swift
//  Tinkoff Chat
//
//  Created by Динара Аминова on 27.09.2020.
//  Copyright © 2020 AlekseyKudryashov. All rights reserved.
//

import Foundation

struct ConversationsStorage {
    struct AllStorageModel {
        let online: [ConversationCellModel]
        var offline: [ConversationCellModel]
    }
    
    static let allStorage = AllStorageModel.init(online: [ConversationCellModel(name: "Ronald Robertson",
                                                                       message: "An suas viderer pro. Vis cu magna altera, ex his vivendo atomorum.",
                                                                       date: Date(),
                                                                       isOnline: true,
                                                                       hasUnreadMessages: true),
                                                 ConversationCellModel(name: "Johnny Watson",
                                                                       message: "Reprehenderit mollit excepteur labore deserunt officia laboris eiusmod cillum eu duis.",
                                                                       date: Date(timeIntervalSinceNow: -400),
                                                                       isOnline: true,
                                                                       hasUnreadMessages: true),
                                                 ConversationCellModel(name: "Martha Craig",
                                                                       message: "Aliqua mollit nisi incididunt id eu consequat eu cupidatat.",
                                                                       date: Date(timeIntervalSinceNow: -142330),
                                                                       isOnline: true,
                                                                       hasUnreadMessages: false),
                                                 ConversationCellModel(name: "Lionel Messi",
                                                                       message: "",
                                                                       date: Date(timeIntervalSinceNow: -245400),
                                                                       isOnline: true,
                                                                       hasUnreadMessages: false),
                                                 ConversationCellModel(name: "Cristiano Ronaldo",
                                                                       message: "Have you got a ball?",
                                                                       date: Date(timeIntervalSinceNow: -28030),
                                                                       isOnline: true,
                                                                       hasUnreadMessages: false),
                                                 ConversationCellModel(name: "Lebron James",
                                                                       message: "",
                                                                       date: Date(timeIntervalSinceNow: -340230),
                                                                       isOnline: true,
                                                                       hasUnreadMessages: false),
                                                 ConversationCellModel(name: "Eminem",
                                                                       message: "I'm just arived from Russia.",
                                                                       date: Date(timeIntervalSinceNow: -4000),
                                                                       isOnline: true,
                                                                       hasUnreadMessages: false),
                                                 ConversationCellModel(name: "Tinkoff Chat",
                                                                       message: "You got a five mark for this task.",
                                                                       date: Date(timeIntervalSinceNow: -4750),
                                                                       isOnline: true,
                                                                       hasUnreadMessages: false),
                                                 ConversationCellModel(name: "Ilia Dudarenko",
                                                                       message: "We are ready to take you in our team.",
                                                                       date: Date(timeIntervalSinceNow: -6846),
                                                                       isOnline: true,
                                                                       hasUnreadMessages: false),
                                                 ConversationCellModel(name: "Pavel Durov",
                                                                       message: "How does is VK lives there?",
                                                                       date: Date(timeIntervalSinceNow: -8419),
                                                                       isOnline: true,
                                                                       hasUnreadMessages: false)],
                                        offline: [ConversationCellModel(name: "Arthur Bell",
                                                                        message: "Voluptate irure aliquip consectetur commodo ex ex.",
                                                                        date: Date(timeIntervalSinceNow: -14000),
                                                                        isOnline: false,
                                                                        hasUnreadMessages: false),
                                                  ConversationCellModel(name: "Jane Warre",
                                                                        message: "Ex Lorem veniam veniam irure sunt adipisicing culp.",
                                                                        date: Date(timeIntervalSinceNow: -183090),
                                                                        isOnline: false,
                                                                        hasUnreadMessages: true),
                                                  ConversationCellModel(name: "Morris Henry",
                                                                        message: "",
                                                                        date: Date(timeIntervalSinceNow: -240500),
                                                                        isOnline: false,
                                                                        hasUnreadMessages: false),
                                                  ConversationCellModel(name: "Irma Flores",
                                                                        message: "Amet enim do laborum tempor nisi aliqua ad adipisicing.",
                                                                        date: Date(timeIntervalSinceNow: -3125500),
                                                                        isOnline: false,
                                                                        hasUnreadMessages: false),
                                                  ConversationCellModel(name: "Colin Williams",
                                                                        message: "Dolore veniam Lorem occaecat veniam irure laborum est amet.",
                                                                        date: Date(timeIntervalSinceNow: -934760),
                                                                        isOnline: false,
                                                                        hasUnreadMessages: true),
                                                  ConversationCellModel(name: "Barak Obama",
                                                                        message: "I'm in Oklahoma right now.",
                                                                        date: Date(timeIntervalSinceNow: -44050),
                                                                        isOnline: false,
                                                                        hasUnreadMessages: true),
                                                  ConversationCellModel(name: "My mom",
                                                                        message: "I love you.",
                                                                        date: Date(timeIntervalSinceNow: -64000),
                                                                        isOnline: false,
                                                                        hasUnreadMessages: false),
                                                  ConversationCellModel(name: "Dinara Aminova",
                                                                        message: "Can you buy some vegetables, pls?.",
                                                                        date: Date(timeIntervalSinceNow: -78000),
                                                                        isOnline: false,
                                                                        hasUnreadMessages: false),
                                                  ConversationCellModel(name: "Yandex taxi",
                                                                        message: "",
                                                                        date: Date(timeIntervalSinceNow: -86000),
                                                                        isOnline: false,
                                                                        hasUnreadMessages: false),
                                                  ConversationCellModel(name: "Megafon",
                                                                        message: "Happy birthday to you",
                                                                        date: Date(timeIntervalSinceNow: -140000),
                                                                        isOnline: false,
                                                                        hasUnreadMessages: false)])
}
